---
title: "01-introductions"
output: html_document
css: style.css
---

## Housekeeping

* For next week, HW-1: Restoration goals and outcomes. Available in Google Classroom. Submit there.
* In two weeks (Fri 9/19) we will conduct SAV monitoring using the SAV Watchers protocol at St. Inigoes Landing. We'll have to wade into the water from a beach. There is usually SAV in knee-deep water at this site as well as waist to chest deep depending on the tide. If you feel comfortable wading into deeper water, wear a bathing suit and quick-dry shorts/tights/shirt. Otherwise just wear comfortable clothes you don't mind getting a little wet. **Everyone needs to wear shoes in the water. Dive booties or water shoes are ideal, tevas/chacos or crocs are ok. No flip-flops. Bring a towel to dry off and sit on in the van.** 

## Learning objectives

* Explain the linkages between the Chesapeake Watershed Agreement Goals and Outcomes and coastal monitoring
* Explain whether we are on track to meeting particular Goals and Outcomes and how we know whether we are on track
* List basic water quality parameters and how they relate the Goals and Outcomes


## Resources

* [Slides](https://docs.google.com/presentation/d/12BiPZ5xwq_SSQtvFhpmQ2TJtIKfxdZr2pRuQdX0EoTU/edit#slide=id.p)
* [Chesapeake Bay Watershed Agreement](https://d18lev1ok5leia.cloudfront.net/chesapeakebay/Chesapeake-Bay-Watershed-Agreement-Amended.pdf)
* [Chesapeake Progress](https://www.chesapeakeprogress.com/)
* [Eyes on the Bay](https://eyesonthebay.dnr.maryland.gov/)

## Lesson plan

### 1. Introductions
 
* Share name & pronouns, major(s)/minor(s), fun fact about you that not a lot of people know.

### 2. Course logistics

* Course website url: [https://smr-monitoring.github.io/MRNE395-2025FA/](https://smr-monitoring.github.io/MRNE395-2025FA/). Bookmark this link - it has everything you need for the class.
* The [syllabus](https://smr-monitoring.github.io/MRNE395-2025FA/syllabus.html) contains information on assessment and class policies.
* The [schedule](https://smr-monitoring.github.io/MRNE395-2025FA/schedule.html) is our master organizer. All assignments, slides, etc. are linked here by date.
* The [SOPs](https://smr-monitoring.github.io/MRNE395-2025FA/sops.html) page contains links to all of the standard operating procedures we'll use to conduct our monitoring program

### 3. Intro to coastal monitoring

<iframe src="https://docs.google.com/presentation/d/12BiPZ5xwq_SSQtvFhpmQ2TJtIKfxdZr2pRuQdX0EoTU/embed?start=false&loop=false&delayms=5000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>
