---
title: "NPP calculations and YSI calibration"
output: html_document
css: style.css
---

## Housekeeping

* HW for next week: be able to tie the bowline, lobster buoy hitch, and half hitch. You can use a guide but you'll need to be able to tie the knots quickly.
* Next week we will learn how to program and deploy continuous monitoring instruments. We will meet in the lab and then go down to the water to deploy instruments.

## Learning objectives

* Tie a lobster bowline, lobster buoy hitch, and half hitch knot
* Calculate k~D~ using vertical PAR profile data
* Calculate percent light through the shade (PLS)
* Calculate NPP, GPP, and R using bottle measurements
* Estimate "depth" of shade treatments using k~D~ and PLS
* Calibrate YSI pH, DO, and conductivity

## Lesson plan

1. Go over homework
2. NPP review and how to do calculations
<iframe src="https://docs.google.com/presentation/d/1vVPUwls3ZBK63PpV9ByoBsd7anS2p0VLJc3WxIrWn5c/embed?start=false&loop=false&delayms=5000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>

3. Enter data and do NPP calculations

    [Link to data folder](https://drive.google.com/drive/folders/1Oqr4Gpjc2pENiwlXDxtjsYyvc014ibwh?usp=drive_link)

4. YSI calibration
