---
title: "01-introductions"
output: html_document
css: style.css
---

## Housekeeping

* **Homework for next week:** Each person in your group should stop by your monitoring station at least once between now and next Friday. Come up with a schedule now to space your visits apart. Each member should fill out the **[Monitoring station site visit form]()** during your visit. You should add the Google Drive app to your phone.
* **Lab next week:** We will retrieve our CONMON loggers next week so be prepared to be outside for part of the time

## Learning objectives

* Define *discrete* and *continuous* data
* Describe factors that should be considered when selecting a continuous monitoring site
* Describe factors that should be considered when designing a continuous monitoring system (which variables to measure, installation design, etc.)
* Calibrate and program continuous water quality data loggers
* Safely deploy a continuous monitoring station consisting of a series of data loggers

## Resources

* [USGS TM1-D3](https://pubs.usgs.gov/tm/2006/tm1D3/pdf/TM1D3.pdf)
* [Slides](https://docs.google.com/presentation/d/1G7hgNhtZciZUJGy8lcRW-A57cRLWK2LmEA4Hlgndnng/)
* [logger deployment data sheet](https://docs.google.com/spreadsheets/d/13Th59bvqzj5W5UKwX2BDcOht2YbG9D7KuRu2FcLsj6o/edit?usp=sharing)

## Lesson plan

1. CONMON slides
<iframe src="https://docs.google.com/presentation/d/1G7hgNhtZciZUJGy8lcRW-A57cRLWK2LmEA4Hlgndnng/embed?start=false&loop=false&delayms=5000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>

2. [Monitoring station design and logger programming](https://docs.google.com/document/d/1Qx_HaF-c_is4Q0hbecdqUGVlL5uSHxrcEJDDVACsp28/edit)

3. Install monitoring stations
