---
title: "Continuous monitoring - retrieval"
output: html_document
css: style.css
---

## Housekeeping

* HW 7 for next week: Tie a cleat hitch (you'll need to practice this one at the waterfront); tie the clove hitch, bowline, lobster buoy hitch faster and with more confidence. Practice tying them, especially the bowline, around different objects and from different angles.


## Learning objectives

* Safely retrieve loggers following SOPs
* Properly clean fouled loggers
* Download and process logger data
* Correct logger data for fouling and sensor drift
* Save logger data to shared folder using consistent naming convention

## Resources

* [PME MiniDOT logger SOP](https://smr-monitoring.github.io/sop/do-logger-pme.html)
* [HOBO pH logger SOP](https://smr-monitoring.github.io/sop/ph-logger-hobo.html)
* [Data folder](https://drive.google.com/drive/folders/1HenKOqVGsJ_j6egivQh6nvkLq1Wx2ayf?usp=sharing)
* [USGS TM1D3](https://pubs.usgs.gov/tm/2006/tm1D3/pdf/TM1D3.pdf)

## Supplies

* bins for loggers (2)
* scissors or snips
* squirt bottles with DI water
* paper towels
* YSI
* printed logger retrieval logsheets (2)
* bag or bin for used zip ties
* scrub brushes
* pH 7 buffer

## Lesson plan

1. Slides on fouling and sensor drift corrections 
<iframe src="https://docs.google.com/presentation/d/1MpLZJBUzWRgV7FLXTM75yRtSHC6TObAQW2D5VXuunL0/embed?start=false&loop=false&delayms=5000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>


## Procedures

1. Calibrate pH and DO on the YSI.

1. Retrieve loggers
    * Get logger caps, data sheet, clip board/pencil, plastic tub, scissors/snippers, and waders. 
    * Walk down to the waterfront.
    * As you approach your loggers, try not to stir up the bottom - you don't want to mess up your fouling drift measurements.
    * Place the YSI in the water near your logger. Record the DO and pH on your datasheet under "fouling correction YSI - dirty". Leave the sonde in the water.
    * Pull loggers out of water (still connected to concrete block) and note time on data sheet.
    * Clean loggers using DI squirt bottle and/or paper towels/brushes.
    * Return loggers to water for fouling drift measurement, note time on data sheet, and allow to sit for at least 15 minutes (enjoy the weather in the meantime).
    * Before pulling the loggers from the water, record the YSI DO, pH, and salinity again under "fouling correction YSI - clean".
    * Retrieve loggers, note the time on your data sheet, and remove from concrete block - don't cut reusable zip ties.
    * Scrub the block in the river water.
    * Return blocks to Schaefer loading bay and clean with the hose (leave in the loading bay area to dry).
    * Return waders to SH basement.
    * Return to lab with loggers and remaining gear.
<br>
<br>
1. Back at the lab, clean loggers using tap water and scrub gently if needed, avoiding the sensor. Dry them well using paper towels. Be sure to also dry the inside rims and threads of the DO logers as soon as you open them.

1. Rinse the pH sensor with DI water then with pH 7 buffer. Connect to logger with the Hobo Connect mobile app so you can see the realtime data. Place logger into pH 7 solution. 

1. When the readings equilibrate, record the reading on your data sheet while in pH 7 solution under "drift correction standard reading."

1. Enter the data from your field data sheet into the `conmon_deployment_log` spreadsheet linked in the Resources section above.

1. Process and download data as specified in the SOPs linked in the Resources section above. 
    * The DO data will download as a .txt file onto your computer. Make sure you know where on your computer the file is saved. You'll need to import it into Excel on your computer first, then save it as a .csv file on your computer.
    * Save the pH DO .csv files in the shared data folder linked above. 
    * Use the following naming convention: `yyyy_mm_dd_parameter_group-letter` (all lowercase, with an underscore (`_`) in place of spaces; use date of deployment for the date). Your group letter is the letter on your buoy.
    * e.g., `2024-09-27_do_a` or `2024-09-27_light_a`
<br>
<br>

1. Clean pH data and determine if fouling and calibration drift correction is needed (offset is greater than or equal to ± 0.2 pH unit):

    - Right-click on your group's pH .csv file and select `Open with / Google Sheets.`
    - Find the most recent pH measurement collected before you removed the loggers for cleaning - this will be M~b~ (monitor before cleaning). If the measurement was < ~1 minute before you removed it, find the measurement before that (you may have stirred up the bottom when approaching the sensor array).
    - Find the most recent pH measurement collected after you placed the loggers back into the water. This will M~a~ (monitor after cleaning).
    - If your YSI (field sensor) readings changed before (F~b~) and after (F~a~) cleaning the loggers, we need to take that into account.
    - Your total fouling drift correction factor is (M~a~ - M~b~) - (F~a~ - F~b~). 
    - Your calibration drift correction factor is the logger reading in the standard (V~c~) subtracted from the standard value (V~s~ = 7) (V~s~ - V~c~ = 7 - V~c~).
    - Your total correction factor is the total fouling drift + total calibration drift.
    - Delete any rows of data collected before you deployed the loggers and after you pulled them from the water to clean them (the times are on your field data sheet). Delete any extraneous columns (#, Button Down/Up, Host Connected, Stopped, End of File).
    - Calculate the slope and intercept of your offset (CG will walk you through this in the beginning of class).
    - Add a new column called offset and use the slope and intercept to calculate the offset.
    - Add a new column called ph_corrected. Calculate the corrected pH values by multiplying each raw pH measurement by the prorated offset.
    - Plot your raw and corrected data to make sure everything looks ok.
    - If the correction factor is +/- 0.2 or greater, calculate the offset slope and intercept and apply the correction by adding the offset to the raw pH values. If the correction factor is less than +/- 0.2, you don't need to apply a correction factor. 
<br>
<br>
1. Clean DO data and determine if fouling drift correction is required (offset is greater than or equal to ±0.3 mg/L)

    - Right-click on your group's oxygen csv file and select Open with / Google Sheets.
    - Find the most recent DO (mg/l) measurement collected before you removed the loggers for cleaning - this will be M~b~ (monitor before cleaning). If the measurement was < ~1 minute before you removed it, find the measurement before that (you may have stirred up the bottom when approaching the sensor array).
    - Find the most recent DO measurement (mg/l) collected after you placed the loggers back into the water. This will M~a~ (monitor after cleaning).
    - Your fouling drift correction factor is M~a~ - M~b~ - (F~a~ - F~b~).
    - Delete any rows of data collected before you deployed the loggers and after you pulled them from the water to clean them (the times are on your field data sheet).
    - If the correction factor is +/- 0.3 mg/l or greater, calculate the offset slope and intercept and apply the correction by adding the offset to the raw DO values. If the correction factor is less than +/- 0.3 mg/l, you don't need to apply a correction factor. 
    - If you applied a correction factor to your DO (mg/l) data, repeat for DO (percent).
    - Plot your raw and corrected data to make sure everything looks ok.

<br>
<br>
